#!/bin/bash
sudo apt install wget
MANIFEST=https://github.com/Palladium-OS/platform_manifest
BRANCH=11

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "CoolGuyMK"
git config --global user.email coolguymk1@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

pwd
ls

#delete files below and sync your own sauces
git clone --depth=1 --single-branch https://github.com/CoolGuyMK/device-xiaomi-davinci.git -b palladium device/xiaomi/davinci
git clone --depth=1 --single-branch https://github.com/Laker87/VantomKernel -b VantomKernel-R5 kernel/xiaomi/sm6150
git clone --depth=1 --single-branch https://github.com/CoolGuyMK/vendor-xiaomi-davinci.git -b eleven vendor/xiaomi/davinci
