#!/bin/bash
sudo apt install wget
MANIFEST=https://github.com/ColtOSTemp/platform_manifest
BRANCH=c11

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "CoolGuyMK"
git config --global user.email coolguymk1@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

pwd
ls

#delete files below and sync your own sauces
git clone --depth=1 --single-branch https://github.com/CoolGuyMK/device-xiaomi-davinci-colt.git  device/xiaomi/davinci
git clone --depth=1 --single-branch https://github.com/Laker87/VantomKernel -b VantomKernel-R3 kernel/xiaomi/sm6150
git clone --depth=1 --single-branch https://github.com/CoolGuyMK/vendor-xiaomi-davinci.git -b eleven vendor/xiaomi/davinci
rm -rf hardware/qcom-caf/sm8150/audio && rm -rf hardware/qcom-caf/sm8150/display && rm -rf hardware/qcom-caf/sm8150/media && rm -rf hardware/xiaomi
git clone https://github.com/CoolGuyMK/hardware-qcom-caf-sm8150-display hardware/qcom-caf/sm8150/display
git clone https://github.com/CoolGuyMK/hardware-qcom-caf-sm8150-audio hardware/qcom-caf/sm8150/audio
git clone https://github.com/CoolGuyMK/hardware-qcom-caf-sm8150-media hardware/qcom-caf/sm8150/media
git clone https://github.com/LineageOS/android_hardware_xiaomi hardware/xiaomi 
git clone https://github.com/kdrag0n/proton-clang prebuilts/clang/host/linux-x86/clang-proton --depth=13 && cd prebuilts/clang/host/linux-x86/clang-proton && git reset --hard 8663d1ddacc7b832a5668cc4734d2060b2998e3c && cd .. && cd .. && cd .. && cd .. && cd ..
